feat: add trap handlers in lint

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -2,13 +2,40 @@
 require() {
   hash "$@" || exit
 }
+
+# shellcheck disable=SC2317
+# Don't warn about unreachable commands in this function
+handle_error() {
+  # Get information about the error
+  local error_code=$?
+  local error_command="$BASH_COMMAND"
+
+  # Log the error details
+  echo -e "${RED}An error occurred at ${error_command} (exit code: ${error_code})${ENDCOLOR}"
+  exit "$error_code"
+}
+
+# shellcheck disable=SC2317
+# Don't warn about unreachable commands in this function
+ctrl_c() {
+  # Get information about the error
+  local error_code=$?
+  local error_command="$BASH_COMMAND"
+  echo -e "${RED}Script interrupted at ${error_command} (exit code: ${error_code})${ENDCOLOR}"
+  exit 1
+}
+
+set -e
+set -o pipefail
+set -u
+trap handle_error ERR
+trap ctrl_c INT
 require date htmlhint stylelint prettier tidy find parallel colorguard html-validate js-beautify nproc
 start=$(date +%s)
-#RED="\e[31m"
+RED="\e[31m"
 GREEN="\e[32m"
 ENDCOLOR="\e[0m"
 echo -e "${GREEN}Starting...${ENDCOLOR}"
-set -e
 declare -i SUCCESS=0
 declare -i STYLE_SUCCESS=0
 declare -r configFileName="tidy.config"
@@ -91,5 +118,5 @@ echo -e "${GREEN}Executing prettier for svg...${ENDCOLOR}"
 prettier --cache --parser html --write -- **/*.svg
 SUCCESS=$((SUCCESS + $?))
 end=$(date +%s)
-echo -e "${GREEN}Execution time was $((end - start)) seconds.${ENDCOLOR}"
+echo -e "${GREEN}Execution time: $((end - start)) seconds.${ENDCOLOR}"
 exit $((SUCCESS + STYLE_SUCCESS))
